name: Bug Report
description: Report broken links, build issues, or interactive component bugs
labels: ["type: bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What's Broken?
      description: Describe the bug clearly
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can someone reproduce this?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if they help explain the problem
    validations:
      required: false
