name: Content Improvement
description: Suggest improvements to an existing guide
labels: ["type: content"]
body:
  - type: dropdown
    id: guide
    attributes:
      label: Which Guide?
      description: Select the guide that needs improvement
      options:
        - "Linux Essentials: Shell Basics"
        - "Linux Essentials: Streams and Redirection"
        - "Linux Essentials: Text Processing"
        - "Linux Essentials: Finding Files"
        - "Linux Essentials: File Permissions"
        - "Linux Essentials: Job Control"
        - "Linux Essentials: Scripting Fundamentals"
        - "Linux Essentials: Disk and Filesystem"
        - "Linux Essentials: Networking"
        - "Linux Essentials: System Information"
        - "Linux Essentials: Archiving and Compression"
        - "Linux Essentials: Best Practices"
        - "DNS Administration: DNS Fundamentals"
        - "DNS Administration: Zone Files and Records"
        - "DNS Administration: DNS Tools and Troubleshooting"
        - "DNS Administration: BIND"
        - "DNS Administration: NSD and Unbound"
        - "DNS Administration: PowerDNS"
        - "DNS Administration: DNSSEC"
        - "DNS Administration: DNS Architecture and Operations"
        - "Git: Introduction"
        - "Git: The Three Trees"
        - "Git: Commits and History"
        - "Git: Branches and Merging"
        - "Git: Remote Repositories"
        - "Git: Rewriting History"
        - "Git: Stashing and the Worktree"
        - "Git: Configuring Git"
        - "Git: The Object Model"
        - "Git: Refs, the Reflog, and the DAG"
        - "Git: Transfer Protocols"
        - "Git: Collaboration Workflows"
        - "Git: Platforms"
        - "Git: Hooks and Automation"
        - "Git: Security"
        - "Git: Monorepos and Scaling"
        - "Git: Troubleshooting and Recovery"
        - "Databases: InnoDB Recovery (PDRT)"
        - "Perl: Introduction"
        - "Perl: Scalars, Strings, and Numbers"
        - "Perl: Arrays, Hashes, and Lists"
        - "Perl: Control Flow"
        - "Perl: Regular Expressions"
        - "Perl: Subroutines and References"
        - "Perl: File I/O and System"
        - "Perl: Modules and CPAN"
        - "Perl: Object-Oriented Perl"
        - "Perl: Error Handling and Debugging"
        - "Perl: Testing"
        - "Perl: Text Processing and One-Liners"
        - "Perl: Networking and Daemons"
        - "Perl: Web Frameworks and APIs"
        - "Perl: Developer Roadmap"
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: What Needs Improving?
      description: Describe what's wrong or missing
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Content
      description: What should it look like after improvement? Include specific text, examples, or references if possible.
    validations:
      required: false
