DROP EXTENSION pg_net;
DROP EXTENSION pg_graphql;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;
CREATE TABLE public.runbook_progress (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, progress jsonb DEFAULT '{}'::jsonb NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.runbook_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runbook_progress ADD CONSTRAINT runbook_progress_pkey PRIMARY KEY (id);
ALTER TABLE public.runbook_progress ADD CONSTRAINT runbook_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.runbook_progress ADD CONSTRAINT runbook_progress_user_id_key UNIQUE (user_id);
GRANT ALL ON public.runbook_progress TO anon;
GRANT ALL ON public.runbook_progress TO authenticated;
GRANT ALL ON public.runbook_progress TO service_role;
CREATE INDEX idx_runbook_progress_user_id ON public.runbook_progress (user_id);
CREATE POLICY "Users insert own progress" ON public.runbook_progress FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users read own progress" ON public.runbook_progress FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users update own progress" ON public.runbook_progress FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
