name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcairo2-dev libffi-dev

      - name: Install dependencies
        run: pip install -r requirements-test.txt

      - name: Install JS dependencies
        run: npm ci

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify
        run: ./verify.sh
